// <auto-generated />
using System;
using Assembly.Site.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assembly.Site.Migrations
{
    [DbContext(typeof(JAADBContext))]
    [Migration("20231113222659_InitialDBCreation")]
    partial class InitialDBCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assembly.Site.Data.Models.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<int>("DeviceType")
                        .HasColumnType("int")
                        .HasColumnName("TYPE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("DeviceID");

                    b.ToTable("DEVICES");
                });

            modelBuilder.Entity("Assembly.Site.Data.Models.Operation", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationID"));

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<int>("OrderInWhichToPerform")
                        .HasColumnType("int")
                        .HasColumnName("PIORITY");

                    b.HasKey("OperationID");

                    b.HasIndex("DeviceID");

                    b.ToTable("OPERATIONS");
                });

            modelBuilder.Entity("Assembly.Site.Data.Models.Operation", b =>
                {
                    b.HasOne("Assembly.Site.Data.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceID");

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
